#!/usr/bin/env ruby

require 'cloudstack_ruby_client'

require 'yaml'
csconfig = YAML::load_file("csconfig.yaml")

URL = csconfig[:url]
APIKEY = csconfig[:apikey]
SECKEY = csconfig[:seckey]

client = CloudstackRubyClient::Client.new(URL,APIKEY,SECKEY, false)

zones = client.list_zones

zones['zone'].each do |z|
  printf "%-31s %-10s %-37s\n" % [ z['name'], nil, z['id'] ]
end
