#!/usr/bin/env ruby

require 'cloudstack_ruby_client'

require 'yaml'
csconfig = YAML::load_file("csconfig.yaml")

URL = csconfig[:url]
APIKEY = csconfig[:apikey]
SECKEY = csconfig[:seckey]

client = CloudstackRubyClient::Client.new(URL,APIKEY,SECKEY, false)

serviceofferings = client.list_service_offerings

serviceofferings['serviceoffering'].each do |s|
  printf "%-31s %-10s %-37s\n" % [ s['name'], nil, s['id'] ]
end
