#!/usr/bin/env ruby

require 'cloudstack_ruby_client'
require 'yaml'
csconfig = YAML::load_file("csconfig.yaml")

URL = csconfig[:url]
APIKEY = csconfig[:apikey]
SECKEY = csconfig[:seckey]

client = CloudstackRubyClient::Client.new(URL,APIKEY,SECKEY, false)

iterator = 1
pagesize = 20 # max 500
vms = []

search_key = 'keyword'
search_value = ARGV[0]

count = client.list_virtual_machines({'listall' => 'true', search_key => search_value})['count']

total_pages = (count.to_f / pagesize).ceil

while (iterator <= total_pages) do
  vcur = client.list_virtual_machines({'page' => iterator, 'pagesize' => pagesize, search_key => search_value})
    vcur['virtualmachine'].each do |vm|
      vms << vm
    end
    iterator +=1
end

vms.each do |vm|
  printf "%-45.45s %-20.20s %-30.30s %-15.15s %-40.40s\n" % [ vm['displayname'], vm['state'], vm['templatename'], vm['nic'][0]['ipaddress'], vm['id'] ]
end
